package net.thumbtack.school.ttschool;

public enum TrainingErrorCode {

	TRAINEE_WRONG_FIRSTNAME, TRAINEE_WRONG_LASTNAME, TRAINEE_WRONG_RATING, TRAINEE_NOT_FOUND, GROUP_WRONG_NAME,
	GROUP_WRONG_ROOM, SCHOOL_WRONG_NAME, DUPLICATE_GROUP_NAME, GROUP_NOT_FOUND, DUPLICATE_TRAINEE, EMPTY_TRAINEE_QUEUE

}
