DROP DATABASE IF EXISTS ttschool;
CREATE DATABASE `ttschool`; 
USE `ttschool`;

CREATE TABLE school (`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  UNIQUE KEY (`name`, `year`)) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `group` (`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `schoolId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `room` VARCHAR(45) NOT NULL,
  UNIQUE KEY (`name`, `room`),
  FOREIGN KEY (`schoolId`) REFERENCES `school`(id) ON DELETE CASCADE
	) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE subject (`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL
  ) ENGINE=INNODB DEFAULT CHARSET=utf8;
  
CREATE TABLE subjectGroup (`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
`groupId` INT NULL,
`subjectId` INT NULL,
FOREIGN KEY (`groupId`) REFERENCES `group` (id) ON DELETE CASCADE,
FOREIGN KEY (`subjectId`) REFERENCES `subject` (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE trainee (`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `groupId` INT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `rating` INT NOT NULL,
  KEY firstName(firstName),
  KEY lastName(lastName),
  FOREIGN KEY (`groupId`) REFERENCES `group` (id) ON DELETE SET NULL
  ) ENGINE=INNODB DEFAULT CHARSET=utf8;